### PR TITLE
Add ReFrame test suite for compatibility layer

### LINKED ISSUE #42: Validate the state of the compatibility layer.
We probably should have something validate the compatibility layer to ensure that it is ready to accept software.  There are some installed pieces of software exists, but is there software we wish to ensure isn't present as well?

Also, this script may be extended to verify a new version of the compatibility layer for release, but stripping caches and such?

### PR DESCRIPTION
**Pull request by bedroge**
Closes #42.

It is being run as part of the existing Github Action. We can also add it as a final step to the installation playbook.

### CODE REVIEW

**Comment by boegel** [comment]
@victorusu Could you take a quick look at it, and see if we could easily move this to ReFrame instead?

The idea would be to run this after the installation of the compat layer, and also in CI (hourly cron for example).

**Comment by victorusu** [comment]
@boegel and @bedroge, yes! 
These tests are classical examples of tests that ReFrame can run. We actually run similar ones at CSCS too.
Do you guys want help to migrate them?

**Comment by boegel** [comment]
@victorusu That would be nice!

Could you maybe pick one, and open a PR to @bedroge's `tests` branch to get it running with ReFrame in CC, to see how that would look like?

**Comment by bedroge** [comment]
@victorusu it would indeed be very helpful if you could give some pointers to or examples of existing similar tests, or even help converting one of these to ReFrame :-)

**Comment by bedroge** [comment]
I've converted the pytest tests to ReFrame tests. This was my first attempt to do something with ReFrame, but I shortly discussed with @victorusu if this was the right approach. @victorusu maybe you could take another look / do a review?

I added some environment variables that allow you to control the version/architecture of the EESSI pilot that you want to test. If you have Qemu installed, you could even do it all in one go by setting `EESSI_ARCH=aarch64,x86_64` and `EESSI_VERSION=2020.12,2021.03`; on my local machine this completed without issues:
```
[  PASSED  ] Ran 74/74 test case(s) from 74 check(s) (0 failure(s), 0 skipped)
```

And also the Github Action now runs this for all versions/archs.

**Review by peterstol — APPROVED** [review]
checks work and no additions for a while...

**Pull request merged**
