### PR TITLE
EESSI 2023.06 compat layer w/ OpenSSL 1.1.1 + GCC 10.4.0 (without using gcc-config)

### PR DESCRIPTION
**Pull request by boegel**
This PR builds on top of the changes proposed in #184, #185, #186, joint work with @trz42 .

Complete overview of changes:

* EESSI pilot version bumped to `2023.06`;
* mask `>=dev-libs/openssl-3`, so we get OpenSSL 1.1.1 in compat layer (to avoid problems with [Rust](https://github.com/EESSI/software-layer/issues/257), [Python](https://github.com/EESSI/software-layer/issues/258), [Perl](https://github.com/EESSI/software-layer/issues/259));
* only mask `>=sys-devel/gcc-11`, so we get latest GCC 10.x (10.4.0) as system compiler in compat layer (since GCC 9.x seems to be no longer actively maintained in Gentoo);
* stop using `gcc-config` to control GCC version used in compat layer, since it's not needed (there is only one GCC version thanks to masking of `sys-devel/gcc`), and it's used incorrectly which causes problems (see #187);
* update Gentoo commit to [aab8473aa90e0287553b3348a5c5b17872df4b7b](https://github.com/gentoo/gentoo/commit/aab8473aa90e0287553b3348a5c5b17872df4b7b) (8 June 2023);
* Gentoo Prefix bootstrap script updated to commit [c6db239](https://github.com/gentoo/prefix/commit/c6db239) (2 June 2023);

closes #184, closes #185, closes #186

### CODE REVIEW

**Comment by boegel** [comment]
bot: build arch=x86_64/generic repo=eessi-2023.06-compat
bot: build arch=aarch64/generic repo=eessi-2023.06-compat

**Comment by boegel** [comment]
The bot should be able to build this (cfr. experiment in https://github.com/boegel/compatibility-layer/pull/2), but it will complain that the build failed even though it doesn't, since the procedure to check for a correct build is still hardcoded for the software layer.

The correct tarballs will also have to created manually, because the `bot/build.sh` for the compat layer script tries to create the tarball outside of the build container, which doesn't work since the compat layer version that was built is not available directly via the native `/cvmfs` mount (which may even be missing).

This shouldn't block us from proceeding with the `2023.06` EESSI pilot version however, since we're already making good progress here (thanks to kicking out the `gcc-config` step, #187 is fixed, and hence the bot is able to complete the build autonomously).

**Comment by trz42** [comment]
> bot: build arch=x86_64/generic repo=eessi-2023.06-compat
> bot: build arch=aarch64/generic repo=eessi-2023.06-compat

the following should work (`=` replaced with `:`)
```
bot: build arch:x86_64/generic repo:eessi-2023.06-compat
bot: build arch:aarch64/generic repo:eessi-2023.06-compat
```

**Comment by trz42** [comment]
Above jobs `4939` and `4940` started but the job manager crashes when trying to update the PR comments. Possibly the PAT it uses is not valid anymore :shrug:

**Comment by boegel** [comment]
> Above jobs `4939` and `4940` started but the job manager crashes when trying to update the PR comments. Possibly the PAT it uses is not valid anymore 🤷

More details on the crash:

<details>

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 723, in <module>
    main()
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 704, in main
    job_manager.process_finished_job(known_jobs[fj])
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 557, in process_finished_job
    update_comment(finished_job["comment_id"], pull_request, comment_update)
  File "/mnt/shared/home/bot/eessi-bot-software-layer/tools/pr_comments.py", line 95, in update_comment
    tries=5, delay=1, backoff=2, max_delay=30)
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/retry/api.py", line 101, in retry_call
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter, logger)
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/IssueComment.py", line 131, in edit
    "PATCH", self.url, input=post_parameters
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/issues#update-an-issue-comment"}
```

</details>

**Comment by boegel** [comment]
bot: foobar

**Pull request merged**
