### PR TITLE
Support multiple overlays, use eclass-overrides, bump version to 2021.02

### PR DESCRIPTION
**Pull request by bedroge**
This will add the [Gentoo Science Repository](https://github.com/gentoo/sci), which for instance has lmod.

### CODE REVIEW

**Comment by peterstol** [comment]
it is great to use the ebuilds if available from the science overlay, but the science overlay is not tested to be compatible with a prefix, as was shown with the double prefix bugs in lmod. Moreover we prefer the scientific packages in the software layer. 

Better to keep EESSI simple and contribute back to science, CC and Prefix layers

**Comment by bedroge** [comment]
I asked about the Prefix support for the Lua libraries, and they are working on this now (by patching the installation method for Lua libraries):
https://bugs.gentoo.org/768909
There's a preliminary patch that solves most of the issues, I included a slightly modified version of it in this PR (just temporarily, so we could try to prepare a new pilot version already).

**Comment by bedroge** [comment]
But we can of course also take the ebuild for lmod and add it to our repo, if that's about the only one that we need from the science overlay. We can discuss this during the compatibility layer meeting.

**Comment by bedroge** [comment]
Also added a fix for #70

**Comment by bedroge** [comment]
This should be okay now, except that we need a new package set first to pass (the last step of) the test.

**Comment by bedroge** [comment]
As just discussed in our [brainstorm meeting](https://github.com/EESSI/compatibility-layer/wiki/Brainstorm-meeting-(Feb-16th-2021)), I've removed the science overlay from our config, but left the functionality to possibly add more custom overlays in the future (as it may still be useful).

This PR also adds functionality to allow an overlay to override certain eclass files, which we currently need for `lua-utils.eclass`.

**Comment by bedroge** [comment]
Hmm, the check is marked as successful, but there are still errors during the `pam` installation... I'll take a look.

**Comment by bedroge** [comment]
The test commands were executed sequentially, and if the last one succeeded, the entire action was marked as successful ;-)
I've fixed this, and fixed the failing test command (the installation dir of Lmod was changed), so this should be good to go now.

**Review by peterstol — APPROVED** [review]

**Pull request merged**
