### PR TITLE
add Dockerfile for container image to bootstrap Prefix with

### PR DESCRIPTION
**Pull request by boegel**
~~Draft PR because the README should be updated as well~~

And perhaps we can get rid of the Singularity definition file since it's not needed anymore?

Currently testing whether actually using this container image work, but it's looking good (bootstrap has started):

```
env PYTHON_TARGETS="python3_7" SNAPSHOT_URL="http://cvmfs-s0.eessi-hpc.org/snapshots" CUSTOM_SNAPSHOT="portage-20200909.tar.bz2" singularity run --bind /tmp/$USER/cvmfs:/cvmfs docker://eessi/bootstrap-prefix:centos8
```

I'm not 100% sure the environment variables will be picked up though, any ideas on how to verify that (either in the bootstrap output or post-bootstrap)?

### CODE REVIEW

**Comment by bedroge** [comment]
If it's picking up the snapshot variables, you should see something like this in `stage1.log`:
```
* Python bootstrapped
http://cvmfs-s0.eessi-hpc.org/snapshots
* Fetching portage-20200909.tar.bz2
wget --no-check-certificate http://cvmfs-s0.eessi-hpc.org/snapshots/portage-20200909.tar.bz2
```

**Comment by boegel** [comment]
That's indeed there, thanks!

**Comment by boegel** [comment]
Update: bootstrapping Prefix using this container image worked like a charm.

**Comment by boegel** [comment]
Docker image to bootstrap Prefix now also available for `aarch64`, see https://hub.docker.com/r/eessi/bootstrap-prefix/tags

Testing it with the following command on a 16-core AWS Graviton2 instance (`c6g.4xlarge`):

```shell
mkdir -p /tmp/$USER/cvmfs
env PYTHON_TARGETS="python3_7" SNAPSHOT_URL="http://cvmfs-s0.eessi-hpc.org/snapshots" CUSTOM_SNAPSHOT="portage-20200909.tar.bz2" singularity run --bind /tmp/$USER/cvmfs:/cvmfs docker://eessi/bootstrap-prefix:centos8-arm64v8
```

**Comment by boegel** [comment]
@terjekv @bedroge I think this is good to go now, please do a critical review and check whether more things need to change in the README.

New images with `-x86_64` and `-aarch64` have been pushed to Docker Hub (see https://hub.docker.com/r/eessi/bootstrap-prefix/tags) using the script and `Dockerfile`s included here.

**Review by bedroge — APPROVED** [review]
lgtm

**Pull request merged**
