### PR TITLE
build version EESSI/2023.06

### PR DESCRIPTION
**Pull request by trz42**
- uses Gentoo commit from June 8
- bumps archspec to v0.2.1
- constrains openssl to 1.1.*

Superseedes #184

### CODE REVIEW

**Comment by trz42** [comment]
bot: help

**Comment by trz42** [comment]
Test 1234

**Comment by boegel** [comment]
bot: help

**Comment by boegel** [comment]
bot: help

**Comment by trz42** [comment]
bot: help

**Comment by boegel** [comment]
bot: help

**Comment by boegel** [comment]
was merged via #188

**Pull request merged**
