### PR TITLE
Run the ReFrame tests at the end of the playbook

### PR DESCRIPTION
**Pull request by bedroge**
Tests will fail, first need a PR to fix and bump things for 2021.06 (coming soon...).

### CODE REVIEW

**Comment by boegel** [comment]
CI doesn't actually fail at all, does that make sense?

**Comment by bedroge** [comment]
Ah, the ReFrame step actually failed:
```
TASK [compatibility_layer : Run ReFrame tests] *********************************
409
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "reframe -r -v -c /tmp/compat_layer.py", "failed_when_result": true, "msg": "[Errno 2] No such file or directory: b'reframe'", "rc": 2}
410
```
But we run another command at the end of the action, which did succeed and changed the exit code to 0, so the action thinks it succeeded... I'll change that.

**Comment by boegel** [comment]
CI still passes 🤪

**Comment by bedroge** [comment]
Man, we really don't like passing tests, do we? :-D
I think I figured it out now, probably related to the rescue operation that should reraise the failure. Trying that now...

**Comment by bedroge** [comment]
CI is broken, see #111, let's fix that later...

**Review by boegel — APPROVED** [review]

**Pull request merged**
