### PR TITLE
enable gold USE flag for binutils so ld.gold is installed

### PR DESCRIPTION
**Pull request by boegel**

### CODE REVIEW

**Comment by boegel** [comment]
@bedroge This works as expected now (reinstall of `2021.12` compat layer completed on `aarch64` + `x86_64`, `ppc64le` pending)

**Comment by bedroge** [comment]
It may be a little bit confusing now how the final `package.use` is going to look like: from the actual task I understand that `prefix_use_flags` will be used during stage1-3, and then the `package.use` will be overwritten by `prefix_bootstrap_use_flags` if that one is set as well. Is that right?

**Comment by boegel** [comment]
@bedroge Oh, right, using both is not going to end well...

Two options:

* I remove `prefix_use_flags` entirely
* We append rather than overwrite with `prefix_bootstrap_use_flags` 

The first option is way easier, and good enough for now?
Interfering with bootstrap stage 1-3 is probably a bad idea anyway, as we found out the hard way in recent days...

**Comment by bedroge** [comment]
@boegel First option sounds good (enough)!

**Review by bedroge — APPROVED** [review]
Lgtm!

**Pull request merged**
